import { applyRescueReward, randomAnimals, reactionAverage, RESCUE_DURATION_SECONDS, rescueScore } from './engine.js';
import { setProgressSilent } from '../../app/state.js';

let rescueTimerId = null;
function text(language, ko, en) { return language === 'en' ? en : ko; }
function animalName(language, animal) { return language === 'en' && animal.nameEn ? animal.nameEn : animal.name; }
function animalVisual(animal, name) { return animal.image ? `<img src="${animal.image}" alt="${name}">` : `<div class="result-placeholder" aria-label="${name}">${animal.emoji || '🐾'}</div>`; }
export function stopRescueTimer() { if (rescueTimerId) clearInterval(rescueTimerId); rescueTimerId = null; }

export function renderRescue(root, state, handlers) {
  stopRescueTimer();
  const language=state.language==='en'?'en':'ko'; let seconds=RESCUE_DURATION_SECONDS,score=0,combo=0,attempts=0,successes=0,reactions=[],targetStartedAt=performance.now(),finished=false,countdown=3;
  root.innerHTML=`<div class="feature-shell"><header class="feature-header"><button class="back-button" data-home>← ${text(language,'홈','Home')}</button><div class="resource-pill">🌿 <span>${text(language,'자연의 빛','Light of Nature')}</span><strong>${state.progress.light}</strong></div></header><section class="feature-title"><span>🛟</span><div><h1>${text(language,'애니멀 구조대','Animal Rescue')}</h1><p>${text(language,'30초 동안 16마리 중 목표 동물을 빠르게 구조하세요.','Rescue the target animal from a 4×4 grid in 30 seconds.')}</p></div></section><section class="game-scorebar"><strong>⏱ <span id="rescue-time">${seconds}</span></strong><strong>${text(language,'점수','Score')} <span id="rescue-score">0</span></strong><strong>${text(language,'성공','Rescues')} <span id="rescue-success">0</span></strong></section><div id="rescue-countdown" class="party-banner">${countdown}</div><section id="rescue-stage"></section><div id="rescue-result"></div></div>`;
  root.querySelector('[data-home]')?.addEventListener('click',()=>{stopRescueTimer();handlers.onHome();}); const countdownNode=root.querySelector('#rescue-countdown'); const countdownTimer=setInterval(()=>{countdown-=1;if(countdown>0){if(countdownNode)countdownNode.textContent=countdown;return;}clearInterval(countdownTimer);if(countdownNode)countdownNode.textContent=text(language,'구조 시작!','Start Rescue!');nextRound();rescueTimerId=setInterval(()=>{seconds-=1;const node=root.querySelector('#rescue-time');if(node)node.textContent=Math.max(0,seconds);if(seconds<=0)endGame();},1000);},700);
  function nextRound(){if(finished)return;const grid=randomAnimals(16),target=grid[Math.floor(Math.random()*grid.length)];targetStartedAt=performance.now();const stage=root.querySelector('#rescue-stage');if(!stage)return;const targetName=animalName(language,target);stage.innerHTML=`<div class="rescue-target"><span>${text(language,'지금 찾아야 할 동물','Animal to rescue')}</span><strong>${target.emoji} ${targetName}</strong></div><div class="rescue-grid">${grid.map((animal)=>{const name=animalName(language,animal);return `<button type="button" class="rescue-card" data-id="${animal.id}" aria-label="${name}">${animalVisual(animal,name)}<span>${animal.emoji}</span></button>`;}).join('')}</div>`;stage.querySelectorAll('.rescue-card').forEach((button)=>button.addEventListener('click',()=>{if(finished)return;attempts+=1;if(button.dataset.id!==target.id){combo=0;seconds=Math.max(0,seconds-2);button.classList.add('wrong');const timeNode=root.querySelector('#rescue-time');if(timeNode)timeNode.textContent=seconds;if(seconds<=0)endGame();return;}const reaction=(performance.now()-targetStartedAt)/1000;reactions.push(reaction);successes+=1;combo+=1;score+=rescueScore(combo);updateStats();nextRound();}));}
  function updateStats(){const s=root.querySelector('#rescue-score'),r=root.querySelector('#rescue-success');if(s)s.textContent=score;if(r)r.textContent=successes;}
  function endGame(){if(finished)return;finished=true;stopRescueTimer();const next=applyRescueReward(state.progress,score);const gained=next.light-Number(state.progress.light||0);setProgressSilent(next);const lightNode=root.querySelector('.resource-pill strong');if(lightNode)lightNode.textContent=next.light;const accuracy=attempts?Math.round((successes/attempts)*100):0,avg=reactionAverage(reactions),avgText=language==='en'?`${avg.toFixed(2)} sec`:`${Math.floor(avg)}초${String(Math.round((avg%1)*100)).padStart(2,'0')}`;const result=root.querySelector('#rescue-result');if(result)result.innerHTML=`<section class="game-result"><h2>${text(language,'구조 활동 완료','Rescue Complete')}</h2><div class="status-grid"><div class="status-item"><span>${text(language,'점수','Score')}</span><strong>${score}</strong></div><div class="status-item"><span>${text(language,'정확도','Accuracy')}</span><strong>${accuracy}%</strong></div><div class="status-item"><span>${text(language,'평균 반응','Average response')}</span><strong>${avgText}</strong></div><div class="status-item"><span>${text(language,'자연의 빛','Light of Nature')}</span><strong>+${gained}</strong></div></div><button class="again-button" data-again type="button">${text(language,'한 번 더 도전','Try Again')}</button></section>`;result?.querySelector('[data-again]')?.addEventListener('click',handlers.onReplay);}
}
